// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

// Next.js convention: .env.local holds developer secrets and is gitignored.
// Load it after .env so it can override defaults, matching Next.js's own precedence.
// Snapshot + restore shell-exported vars afterward: dotenv's override:true would
// otherwise clobber a value like `$env:DATABASE_URL = "<prod>"` set deliberately
// in the shell (e.g. for a one-off `prisma migrate deploy` against production)
// with whatever .env.local has for local dev — silently running against the
// wrong database instead of erroring.
const shellEnv = { ...process.env };
config();
config({ path: '.env.local', override: true });
Object.assign(process.env, shellEnv);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Migrations run DDL and must use a direct (non-pooled) connection — PgBouncer's
    // transaction-pooling mode (what Supabase's pooled URL uses) doesn't reliably
    // support schema changes. The running app uses DATABASE_URL (pooled) via
    // src/lib/db/client.ts's adapter instead — see .env.example.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
